### ISSUE TITLE
Got different relics from the searching result when playing

### ISSUE THREAD

**Issue by woolen-sheep** [ForgottenArbiter/SeedSearch#2]
For example:
- use the character IRONCLAD(all items unlocked) and the seed "123"(1298)
- choose the path [M, ?, ?, M, M, R, E,](using the default weight)
- "tradeFaces": true
- "neowChoice": 3
- without any other Mods

The mod output the following relicList: [Sozu, SsserpentHead, **White Beast Statue**, Meat on the Bone, StrikeDummy, The Courier, Magic Flower, Eternal Feather, Orichalcum, Boot]
However, when I was playing, I got relic **Bottled Flame** from the first Elite instead of White Beast Statue.

I think a headless game should get the same result as a normal game, what's the problem?

**Comment by ForgottenArbiter** [comment]
Sorry, I was swamped with some stuff at the beginning of quarantine and forgot to respond to this one. The issue is that Bottled Flame only spawns if there is a non-basic attack in your deck. I had a setting to ensure bottled Tornado would show up, but none for Bottled Flame, since it used to count basic attacks and therefore almost always show up. I added a setting to make Bottled Flame always show up (defaulting to true).
