### ISSUE TITLE
wingBootsThreshold

### ISSUE THREAD

**Issue by LLRukia** [ForgottenArbiter/SeedSearch#7]
How to ban wingBoots when searching?
I have tried to set wingBootsThreshold to -100.0, but the map path still unachievable.

**Comment by LLRukia** [comment]
why the code considers whether to use WingBoot or not when we obviously have not got WingBoot?

**Comment by LLRukia** [comment]
Map path:
[M, ?, M, ?, M, R, E, ?, T, ?, R, M, E, S, R, BOSS, M, ?, ?, M, ?, R, ?, M, T, E, ?, ?, S, E, R, BOSS, M, M, ?, S, M, R, E, R, T, R, ?, M, ?, M, R, BOSS]
True map path:
[M, ?/M, M, ?, M, R, E, ?/T, T, ?/T, R, M, E, S, R, BOSS, M, ?, ?/M, M, ?/T, R, ?, M, T, E, ?, ?/M, S, E, R, BOSS, M, M, ?/T, S, M, R, E, R, T, R, ?, M, ?, M, R, BOSS]
![path1](https://user-images.githubusercontent.com/35130995/120286681-1a5ad780-c2f1-11eb-8755-d95e6acfd282.jpg)
![path2](https://user-images.githubusercontent.com/35130995/120286688-1c249b00-c2f1-11eb-9b08-69c065aa82b7.jpg)
![path3](https://user-images.githubusercontent.com/35130995/120286691-1cbd3180-c2f1-11eb-8534-5cebfe0956d8.jpg)

**Comment by LLRukia** [comment]
Sorry, I was wrong. I have tried that delete the "findBootsPath" code and the map path still unachievable. I think the map is different when searching seed but I have no idea how to fix it.

**Comment by ForgottenArbiter** [comment]
I'm confused somewhat by this issue. Wing Boots will never be used in act 1 by SeedSearch because you can't have Wing Boots at the start of act 1. There are very few reasons why the map would be different from what SeedSearch gives you. The only ones I can think of are:

* You're playing on a console or mobile port
* You're playing on a different ascension level

If it's something else, I may be able to help if you post your full SeedSearch settings.

**Comment by LLRukia** [comment]
Thanks for your reply. My fault, I were playing on a different ascension level.

This project is really awesome, helps me a lot.
